name: portfolio_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - yfinance
  - pytest
  - jupyter
  - nb_conda_kernels
  - streamlit=1.31.0
  - plotly=5.18.0